# # See https://symfony.com/doc/current/email/dev_environment.html
# swiftmailer:
#     # send all emails to a specific address
#     #delivery_addresses: ['me@example.com']
#     disable_delivery: true
#     spool: { type: 'memory' }

swiftmailer:
    url: '%env(MAILER_URL)%'
    spool:
        type: file
        path: '%kernel.project_dir%/var/spool'